workspace_root: &workspace_root /home/circleci
workspace_path: &workspace_path workspace
workspace: &workspace /home/circleci/workspace

defaults: &defaults
  working_directory: *workspace
  docker:
    - image: circleci/node:10

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
            - $CACHE_VERSION-dependencies-

      - run:
          name: Install npm dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build package
          command: npm run build

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *workspace_path

  deploy_npm:
    <<: *defaults

    steps:
      - attach_workspace:
          at: *workspace_root

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > "${CIRCLE_WORKING_DIRECTORY}/dist/.npmrc"

      - run:
          name: Publish package
          command: |
            NPM_TAG="latest"
            if [[ ${CIRCLE_TAG} =~ ^v.*-[a-zA-Z]+\.[0-9]+$ ]]; then
            	NPM_TAG="next"
            fi

            npm publish --tag ${NPM_TAG}

  workflows:
    version: 2
    build_and_deploy:
      jobs:
        - build:
            filters:
              tags:
                only: /.*/
              branches:
                ignore:
                  - gh-pages
        - deploy_npm:
            requires:
              - build
            filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v\d+\.\d+\.\d+(-.+)?/